name: CS703
version: 0.1.0.0

extra-source-files:
- README.md
- LICENSE

default-extensions:
- OverloadedStrings

dependencies:
  - containers
  - array
  - base
  - bytestring

executables:
  CS703:
    main-is: Main.hs
    source-dirs: app
    build-depends:
    - CS703

library:
  source-dirs: src
  exposed-modules:
  - Ast
  - Lexer
  - Parser
  - Typing
  - Logic
  build-tools:
  - alex
  - happy

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - filepath
    - directory
    - text
    - hspec >=2.0.0
    - hspec-expectations-lifted
    - CS703
    ghc-options:
    - -Wall
    - -threaded