name: CS703
version: 0.1.0.0

extra-source-files:
- README.md
- LICENSE

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
  - Ast
  - Lexer
  - Parser
  dependencies:
  - containers
  - array
  - base
  - bytestring
  build-tools:
  - alex
  - happy

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - hspec >=2.0.0
    - hspec-expectations-lifted
    - CS703
    ghc-options:
    - -Wall
    - -threaded