name: CS703
version: 0.1.0.0

extra-source-files:
- README.md
- LICENSE

default-extensions:
- OverloadedStrings

dependencies:
  - containers
  - array
  - base
  - bytestring

executables:
  main:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - ghc
    - cmdargs
    - CS703
  debug:
    main: Debug.hs
    other-modules:       []
    source-dirs: scripts
    dependencies:
    - base
    - filepath
    - text
    - hspec >=2.0.0
    - hspec-expectations-lifted
    - CS703
  runtime:
    main: Runtime.hs
    source-dirs: scripts
    other-modules:       []
    dependencies:
    - base
    - filepath
    - directory
    - text
    - clock
    - formatting
    - hspec >=2.0.0
    - hspec-expectations-lifted
    - CS703

library:
  source-dirs: src
  exposed-modules:
  - Ast
  - Lexer
  - Parser
  - Typing
  - Logic
  - Interp
  - Synthesizer
  build-tools:
  - alex
  - happy
  ghc-options:
  - -Wall

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - filepath
    - directory
    - text
    - hspec >=2.0.0
    - hspec-expectations-lifted
    - CS703
    ghc-options:
    - -Wall
    - -threaded